using System;using System.IO;using System.Linq;using System.Text;using System.Threading;using System.Collections.Generic;using System.Diagnostics;using System.Security.Cryptography;using System.Text.RegularExpressions;using System.Web;using System.Web.Script.Serialization;using Microsoft.Playwright;
namespace BranchLab {
public sealed class BranchRuntime : IDisposable {
 readonly JavaScriptSerializer json=new JavaScriptSerializer{MaxJsonLength=16777216};readonly List<Dictionary<string,object>> events=new List<Dictionary<string,object>>();readonly List<string> secrets=new List<string>();
 readonly Dictionary<string,Dictionary<string,object>> results=new Dictionary<string,Dictionary<string,object>>();readonly Dictionary<string,string> output=new Dictionary<string,string>();
 WorkbookPackage package;IPlaywright pw;IBrowser browser;IBrowserContext context;IPage page;string root,baseUrl,runDir,workbook,invocation="",scenario="",step="",itemId="",mode;int round,attempt,seq;bool finished,traceOn,aborted;readonly Stopwatch runClock=Stopwatch.StartNew();
 public string RunId{get;private set;}public string RunDirectory{get{return runDir;}}public string CurrentAccount{get;private set;}public bool LastSucceeded{get;private set;}public string LastOutcome{get;private set;}public string LastError{get;private set;}public int TechnicalErrors{get;private set;}public int RoundDelay{get;private set;}
 public BranchRuntime(string projectRoot){root=Path.GetFullPath(projectRoot);RunId=Guid.NewGuid().ToString("N");runDir=Path.Combine(root,"Results",DateTime.Now.ToString("yyyyMMdd-HHmmss")+"-"+RunId.Substring(0,8));Directory.CreateDirectory(runDir);Directory.CreateDirectory(Path.Combine(runDir,"artifacts"));CurrentAccount="";mode=Environment.GetEnvironmentVariable("BRANCH_TEST_MODE")??"normal";Emit("RunCreated","akaBot","Created","","");Persist(false);}
 public void Initialize(){
  workbook=Environment.GetEnvironmentVariable("BRANCH_WORKBOOK")??Path.Combine(root,"outputs","branch-lab","Branch-Scenarios.xlsx");
  try{
   package=new WorkbookPackage(workbook);baseUrl=Environment.GetEnvironmentVariable("BRANCH_URL")??package.GetSetting("base_url");var uri=new Uri(baseUrl);if(uri.Scheme!="http"&&uri.Scheme!="https")throw new Exception("Invalid base URL");
   RoundDelay=int.Parse(package.GetSetting("round_delay_ms"));if(RoundDelay<0||RoundDelay>60000)throw new Exception("Invalid round delay");int count=int.Parse(package.GetSetting("max_rounds"));if(count<1||count>100)throw new Exception("Invalid max_rounds");
   foreach(var row in package.Items){bool enabled=Enabled(row);var path=Path.GetFullPath(Path.Combine(root,row["file_path"]));if(enabled&&!File.Exists(path))throw new FileNotFoundException("Upload file missing: "+row["_source"]);var cred=Credential(row["credential_ref"]);secrets.Add(cred);results[row["item_id"]]=new Dictionary<string,object>{{"itemId",row["item_id"]},{"branch",row["chi_nhanh"]},{"account",row["account"]},{"enabled",enabled},{"documentId",""},{"status",enabled?"Chưa upload":"Bỏ qua"},{"reason",""},{"error",""},{"history",new List<object>()},{"fileHash",enabled?Hash(File.ReadAllBytes(path)):""}};}
   ValidateVariables();Emit("PackageValidated","runner","Succeeded",Hash(File.ReadAllBytes(workbook)),"");
   pw=Playwright.CreateAsync().GetAwaiter().GetResult();bool headless=Environment.GetEnvironmentVariable("BRANCH_HEADLESS")=="1";
   browser=pw.Chromium.LaunchAsync(new BrowserTypeLaunchOptions{Channel="chrome",Headless=headless,Timeout=30000,SlowMo=headless?0:90}).GetAwaiter().GetResult();
   context=browser.NewContextAsync(new BrowserNewContextOptions{AcceptDownloads=true,ViewportSize=new ViewportSize{Width=1360,Height=900}}).GetAwaiter().GetResult();
   traceOn=Environment.GetEnvironmentVariable("BRANCH_TRACE")=="1";if(traceOn)context.Tracing.StartAsync(new TracingStartOptions{Screenshots=true,Snapshots=true,Sources=false}).GetAwaiter().GetResult();
   page=context.NewPageAsync().GetAwaiter().GetResult();page.PageError+=(s,e)=>Emit("PageError","browser","Warning",Redact(e),"");Emit("RunStarted","akaBot","Running","Native If / ForEach"," ");Persist(false);
  }catch(Exception e){TechnicalErrors++;Emit("InitializationFailed","runner","Failed",Redact(e.Message),"");throw;}
 }
 public object[] GetItems(){return package.Items.Cast<object>().ToArray();}public int[] GetRounds(){return Enumerable.Range(1,int.Parse(package.GetSetting("max_rounds"))).ToArray();}
 static bool Enabled(Dictionary<string,string> r){return r["enabled"]=="1"||r["enabled"].ToLowerInvariant()=="true";}
 public bool ShouldProcess(object item,int checkRound){var r=(Dictionary<string,string>)item;return Enabled(r)&&(checkRound==0||((string)results[r["item_id"]]["status"]=="Chờ duyệt"&&!string.IsNullOrEmpty((string)results[r["item_id"]]["documentId"])));}
 public bool NeedsLogin(object item){return CurrentAccount!=((Dictionary<string,string>)item)["account"];}
 public bool LoggedIn(){return CurrentAccount!="";}
 public bool IsRejected(){return output.ContainsKey("status")&&output["status"]=="Từ chối";}
 public void Prepare(object item,int checkRound){itemId=((Dictionary<string,string>)item)["item_id"];round=checkRound;invocation="";scenario="";step="";attempt=0;Emit("ItemStarted","akaBot","Running",checkRound==0?"Upload":"Status check","");}
 public void Skip(object item,int checkRound){itemId=((Dictionary<string,string>)item)["item_id"];round=checkRound;Emit("BranchSelected","akaBot","Skipped",checkRound==0?"enabled=false":"terminal / no uploaded document","");Emit("ItemFinished","akaBot","Skipped","No browser scenario invoked","");Persist(false);}
 public void Abort(string message){aborted=true;TechnicalErrors++;Emit("WorkflowAborted","akaBot","Failed",Redact(message),"");}
 public void BeginRound(int number){round=number;itemId="";scenario="";step="";Emit("RoundStarted","akaBot","Running","Round "+number,"");}
 public void Branch(string name){Emit("BranchSelected","akaBot","Selected",name,"");}
 public void RecordFailure(){var r=results[itemId];r["error"]=LastError;Emit("ItemFinished","akaBot","Failed",LastError,"");Persist(false);}
 public void RecordUpload(){var r=results[itemId];r["documentId"]=output["document_id"];r["status"]=output["upload_status"];AddHistory(r,"Uploaded","");Emit("ItemFinished","akaBot","Succeeded","Uploaded; initial state=Chờ duyệt","");Persist(false);}
 public void RecordCheck(){var r=results[itemId];r["status"]=output["status"];r["error"]="";AddHistory(r,"Observed","");Emit("ItemStatusObserved","akaBot","Succeeded",output["status"],"");Persist(false);}
 public void CompleteCheck(){Emit("ItemFinished","akaBot","Succeeded","Status and required outputs recorded","");Persist(false);}
 public void RecordReason(){var r=results[itemId];r["reason"]=output["reason"];var h=(List<object>)r["history"];if(h.Count>0)((Dictionary<string,object>)h[h.Count-1])["reason"]=output["reason"];Emit("RejectionReasonExtracted","akaBot","Succeeded",output["reason"],"");Persist(false);}
 void AddHistory(Dictionary<string,object> r,string kind,string reason){((List<object>)r["history"]).Add(new Dictionary<string,object>{{"round",round},{"status",r["status"]},{"reason",reason},{"account",CurrentAccount},{"timestampUtc",DateTime.UtcNow.ToString("o")},{"kind",kind}});}
 public bool Execute(string id,object item,int checkRound){
  var row=(Dictionary<string,string>)item;itemId=row["item_id"];round=checkRound;scenario=id;invocation=Guid.NewGuid().ToString("N");step="";attempt=0;LastSucceeded=false;LastOutcome="";LastError="";output.Clear();var timer=Stopwatch.StartNew();
  if(!package.Scenarios.ContainsKey(id))throw new ArgumentException("Unknown scenario: "+id);var spec=package.Scenarios[id];
  var vars=new Dictionary<string,string>(row);vars["password"]=Credential(row["credential_ref"]);if(mode=="bad_password"&&row["account"]=="cn02")vars["password"]="BadDemoPassword!";secrets.Add(vars["password"]);
  vars["run_id"]=RunId;vars["round"]=checkRound.ToString();vars["document_id"]=(string)results[itemId]["documentId"];vars["file_path"]=Path.GetFullPath(Path.Combine(root,row["file_path"]));vars["file_hash"]=(string)results[itemId]["fileHash"];
  string fault=row["fault_mode"];if(row["account"]=="cn01"&&new[]{"status_silent","upload_fail","response_lost","conflict"}.Contains(mode))fault=mode;
  vars["portal_url"]=baseUrl.TrimEnd('/')+"/branch?run="+RunId+"&seed="+package.GetSetting("seed")+"&fault="+Uri.EscapeDataString(fault);
  if(mode=="wrong_account"&&id=="kiem_tra"&&row["account"]=="cn02")vars["document_id"]=(string)results["HS-01"]["documentId"];
  Emit("ScenarioStarted","runner","Running",id,"");
  try{
   foreach(string input in spec["inputs"].Split(new[]{','},StringSplitOptions.RemoveEmptyEntries))if(!vars.ContainsKey(input)||string.IsNullOrWhiteSpace(vars[input]))throw new Exception("Missing scenario input: "+input);
   foreach(var s in package.Steps.Where(x=>x["scenario_id"]==id).OrderBy(x=>int.Parse(x["order"]))){
    step=s["step_id"];var clock=Stopwatch.StartNew();int max=int.Parse(s["max_retries"]),budget=int.Parse(s["timeout_ms"]);attempt=0;
    Func<float> remaining=()=>{long ms=Math.Min(budget-clock.ElapsedMilliseconds,int.Parse(spec["timeout_ms"])-timer.ElapsedMilliseconds);if(ms<=0)throw new TimeoutException("Step/scenario deadline exceeded");return ms;};
    while(true){attempt++;Emit("StepStarted","runner","Running",s["action"],s["_source"]);
     try{
      page.SetDefaultTimeout(remaining());page.SetDefaultNavigationTimeout(remaining());string value=Resolve(s["value"],vars);ILocator loc=s["target_id"]==""?null:page.Locator(package.Targets[s["target_id"]]["selector"]);
      if(loc!=null&&loc.CountAsync().GetAwaiter().GetResult()>1)throw new InvalidOperationException("AmbiguousSelector: "+s["target_id"]);
      switch(s["action"]){case "navigate":var dest=new Uri(value);if(dest.Scheme!="http"&&dest.Scheme!="https")throw new Exception("Invalid URL scheme");page.GotoAsync(value,new PageGotoOptions{WaitUntil=WaitUntilState.DOMContentLoaded,Timeout=remaining()}).GetAwaiter().GetResult();break;case "fill":loc.FillAsync(value).GetAwaiter().GetResult();break;case "click":loc.ClickAsync().GetAwaiter().GetResult();break;case "upload":loc.SetInputFilesAsync(value).GetAwaiter().GetResult();break;case "read_text":var text=loc.InnerTextAsync().GetAwaiter().GetResult().Trim();if(s["output"]!=""){output[s["output"]]=text;vars[s["output"]]=text;}break;}
      var rules=package.Rules.Where(r=>r["scenario_id"]==id&&r["step_id"]==step).ToList();if(rules.Count>0){var probes=rules.Select(r=>{var c=package.Conditions[r["condition_id"]];return new[]{package.Targets[c["target_id"]]["selector"],c["operator"],Resolve(c["expected"],vars)};}).ToArray();
       while(true){remaining();var matches=page.EvaluateAsync<int[]>(@"cs=>cs.map((c,i)=>{let es=[...document.querySelectorAll(c[0])];if(es.length>1)throw Error('AmbiguousSelector: '+c[0]);let e=es[0],v=!!e&&getComputedStyle(e).visibility!=='hidden'&&getComputedStyle(e).visibility!=='collapse'&&!!(e.getBoundingClientRect().width||e.getBoundingClientRect().height),t=e?(e.innerText||'').replace(/\s+/g,' ').trim():'';let ok=c[1]==='visible'?v:c[1]==='hidden'?!v:c[1]==='text'?v&&t===c[2]:c[1]==='value'?v&&e.value===c[2]:v&&t.length>0;return ok?i:-1;}).filter(i=>i>=0)",probes).GetAwaiter().GetResult();
        if(matches.Length>1)throw new InvalidOperationException("Conflict: multiple outcome conditions matched");if(matches.Length==1){var rule=rules[matches[0]];Emit("ConditionObserved","runner","Matched",rule["condition_id"],s["_source"]);if(rule["effect"]=="retry")throw new RetrySignal();if(rule["effect"]=="fail")throw new InvalidOperationException(rule["outcome"]);if(rule["outcome"]!="")LastOutcome=rule["outcome"];break;}Thread.Sleep((int)Math.Min(80,remaining()));}
      }
      remaining();Emit("StepFinished","runner","Succeeded",s["action"],s["_source"],clock.ElapsedMilliseconds);break;
     }catch(RetrySignal){if(attempt>max)throw new InvalidOperationException("RetryExhausted");Emit("RetryScheduled","runner","Retry",attempt+"/"+max,s["_source"]);Screenshot("retry");Thread.Sleep((int)Math.Min(int.Parse(s["retry_delay_ms"]),remaining()));remaining();}
    }
   }
   foreach(string key in spec["outputs"].Split(new[]{','},StringSplitOptions.RemoveEmptyEntries))if(!output.ContainsKey(key)||string.IsNullOrWhiteSpace(output[key]))throw new Exception("Missing scenario output: "+key);
   if(id=="dang_nhap")CurrentAccount=output["account_seen"];if(id=="dang_xuat")CurrentAccount="";
   LastSucceeded=true;if(LastOutcome=="")LastOutcome=spec["outcome"];Emit("ScenarioFinished","runner","Succeeded",LastOutcome,"",timer.ElapsedMilliseconds);if(id=="tai_len"||id=="kiem_tra"||id=="ly_do_tu_choi")Screenshot("result");return true;
  }catch(Exception e){LastError=e is TimeoutException?"Timeout":Redact(e.Message);TechnicalErrors++;if(id=="dang_nhap"||id=="dang_xuat"||LastError.Contains("SessionExpired"))CurrentAccount="";Emit("StepFinished","runner","Failed",LastError,"",timer.ElapsedMilliseconds);Screenshot("failure");Emit("ScenarioFinished","runner","Failed",LastError,"",timer.ElapsedMilliseconds);return false;}
 }
 sealed class RetrySignal:Exception{}
 string Credential(string reference){if(Regex.IsMatch(reference,"^demo:cn0[1-6]$"))return "BranchDemo!"+reference.Substring(reference.Length-2);if(reference.StartsWith("env:")){string value=Environment.GetEnvironmentVariable(reference.Substring(4));if(!string.IsNullOrEmpty(value))return value;}throw new InvalidDataException("Credential reference missing or unsupported");}
 void ValidateVariables(){var basic=new HashSet<string>(new[]{"account","password","portal_url","item_id","file_path","file_hash","document_id","round","run_id","chi_nhanh","enabled","credential_ref","fault_mode"});foreach(var sc in package.Scenarios.Keys){var available=new HashSet<string>(basic);foreach(var s in package.Steps.Where(x=>x["scenario_id"]==sc).OrderBy(x=>int.Parse(x["order"]))){foreach(Match m in Regex.Matches(s["value"],@"\$\{([^}]+)\}"))if(!available.Contains(m.Groups[1].Value))throw new InvalidDataException(s["_source"]+": undefined variable "+m.Groups[1].Value);if(s["output"]!="")available.Add(s["output"]);foreach(var r in package.Rules.Where(x=>x["scenario_id"]==sc&&x["step_id"]==s["step_id"]))foreach(Match m in Regex.Matches(package.Conditions[r["condition_id"]]["expected"],@"\$\{([^}]+)\}"))if(!available.Contains(m.Groups[1].Value))throw new InvalidDataException(s["_source"]+": undefined condition variable");}}}
 static string Resolve(string value,Dictionary<string,string> vars){return Regex.Replace(value,@"\$\{([^}]+)\}",m=>{if(!vars.ContainsKey(m.Groups[1].Value))throw new ArgumentException("Missing variable: "+m.Groups[1].Value);return vars[m.Groups[1].Value];});}
 string Redact(string s){foreach(string secret in secrets.Where(x=>!string.IsNullOrEmpty(x)).Distinct())s=s.Replace(secret,"[REDACTED]");return s;}
 static string Hash(byte[] b){using(var sha=SHA256.Create())return BitConverter.ToString(sha.ComputeHash(b)).Replace("-","").ToLowerInvariant();}
 void Emit(string type,string source,string status,string detail,string cell,long ms=0){var e=new Dictionary<string,object>{{"eventSchemaVersion","1.0"},{"eventId",Guid.NewGuid().ToString("N")},{"runId",RunId},{"sequence",++seq},{"timestampUtc",DateTime.UtcNow.ToString("o")},{"elapsedMs",runClock.ElapsedMilliseconds},{"source",source},{"eventType",type},{"itemId",itemId},{"round",round},{"invocationId",invocation},{"scenarioId",scenario},{"stepId",step},{"attempt",attempt},{"status",status},{"detail",Redact(detail)},{"sourceCell",cell},{"durationMs",ms}};events.Add(e);File.AppendAllText(Path.Combine(runDir,"events.jsonl"),json.Serialize(e)+Environment.NewLine,new UTF8Encoding(false));string line=DateTime.Now.ToString("HH:mm:ss.fff")+" "+type+" "+itemId+" "+scenario+"/"+step+" "+status+" "+Redact(detail);File.AppendAllText(Path.Combine(runDir,"run.log"),line+Environment.NewLine,new UTF8Encoding(false));Console.WriteLine(line);}
 void Screenshot(string kind){if(page==null)return;try{string relative="artifacts/"+seq.ToString("D5")+"-"+kind+".png";page.ScreenshotAsync(new PageScreenshotOptions{Path=Path.Combine(runDir,relative),FullPage=true,Timeout=3000,Mask=new[]{page.Locator("#password")}}).GetAwaiter().GetResult();Emit("ArtifactCreated","runner","Ready",relative,"");}catch(Exception e){Emit("ArtifactWarning","runner","Warning",Redact(e.Message),"");}}
 int SafeRounds(){int n;return int.TryParse(package.GetSetting("max_rounds"),out n)?n:0;}
 void Persist(bool complete){var record=new Dictionary<string,object>{{"runId",RunId},{"botId","branch_approval"},{"mode",mode},{"dataSource","synthetic"},{"baseUrl",baseUrl},{"headless",Environment.GetEnvironmentVariable("BRANCH_HEADLESS")=="1"},{"process",Process.GetCurrentProcess().ProcessName},{"pid",Process.GetCurrentProcess().Id},{"startedAtUtc",events[0]["timestampUtc"]},{"finishedAtUtc",complete?(object)DateTime.UtcNow.ToString("o"):null},{"durationMs",runClock.ElapsedMilliseconds},{"executionStatus",complete?(aborted?"Aborted":TechnicalErrors==0?"Completed":"CompletedWithIssues"):"Running"},{"technicalErrors",TechnicalErrors},{"workbook",workbook},{"workbookHash",workbook!=null&&File.Exists(workbook)?Hash(File.ReadAllBytes(workbook)):""},{"items",results.Values.ToArray()},{"events",events.Count},{"rounds",package==null||!package.Settings.ContainsKey("max_rounds")?0:SafeRounds()},{"seed",package==null||!package.Settings.ContainsKey("seed")?"":package.GetSetting("seed")}};string dest=Path.Combine(runDir,"results.json");File.WriteAllText(dest+".tmp",json.Serialize(record),new UTF8Encoding(false));if(File.Exists(dest))File.Replace(dest+".tmp",dest,null);else File.Move(dest+".tmp",dest);}
 public void Finish(){if(finished)return;finished=true;try{if(traceOn&&context!=null){context.Tracing.StopAsync(new TracingStopOptions{Path=Path.Combine(runDir,"artifacts","trace.zip")}).GetAwaiter().GetResult();Emit("ArtifactCreated","runner","Ready","artifacts/trace.zip","");}}catch(Exception e){Emit("ArtifactWarning","runner","Warning",e.Message,"");}finally{try{if(context!=null)context.CloseAsync().GetAwaiter().GetResult();if(browser!=null)browser.CloseAsync().GetAwaiter().GetResult();if(pw!=null)pw.Dispose();}catch(Exception e){TechnicalErrors++;Emit("CleanupError","runner","Failed",e.Message,"");}}
  Emit("RunFinished","akaBot",aborted?"Aborted":TechnicalErrors==0?"Completed":"CompletedWithIssues","Technical errors="+TechnicalErrors,"");Persist(true);Report();Console.WriteLine("REPORT="+Path.Combine(runDir,"report.html"));
 }
 public void Dispose(){Finish();}
 static string H(object s){return HttpUtility.HtmlEncode(Convert.ToString(s));}
 void Report(){var b=new StringBuilder("<!doctype html><html lang='vi'><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Báo cáo hồ sơ chi nhánh</title><style>*{box-sizing:border-box}body{font:16px/1.5 Segoe UI,Arial;margin:0;background:#edf2f7;color:#17304e}main{max-width:1300px;margin:36px auto;padding:0 24px}h1{font-size:32px;margin:8px 0}.meta{color:#5b7089;font-size:14px;overflow-wrap:anywhere}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:16px;margin:25px 0}.card{background:white;padding:18px 24px;border:1px solid #d7e1ed;border-radius:8px;min-width:160px}.card strong{display:block;font-size:30px}table{border-collapse:collapse;width:100%;min-width:900px;background:white}th,td{text-align:left;padding:12px;border-bottom:1px solid #dce4ee;vertical-align:top}th{background:#183454;color:white}details{background:white;border:1px solid #dce4ee;margin:14px 0;padding:16px;border-radius:6px;overflow:auto}summary{cursor:pointer;font-weight:600}a{color:#2458cc}code{font-size:12px;overflow-wrap:anywhere}.fail{color:#a13340}.ok{color:#187255}.pending{color:#896520}.scroll{overflow:auto}</style><main><div class='meta'>AKABOT · EXCEL · PLAYWRIGHT .NET</div><h1>Hồ sơ chi nhánh</h1>");
  b.Append("<p>Thực thi: <strong>"+(aborted?"Dừng do lỗi workflow":TechnicalErrors==0?"Hoàn tất":"Hoàn tất có lỗi kỹ thuật")+"</strong>. Trạng thái phê duyệt bên dưới là kết quả nghiệp vụ mô phỏng.</p><p class='meta'>Run "+H(RunId)+" · "+H(events[0]["timestampUtc"])+" · "+H(mode)+" · "+Math.Round(runClock.Elapsed.TotalSeconds,1)+" giây · Seed "+H(package==null||!package.Settings.ContainsKey("seed")?"":package.GetSetting("seed"))+"</p><div class='cards'>");
  foreach(string status in new[]{"Chờ duyệt","Từ chối","Đã hủy","Đã duyệt","Bỏ qua"})b.Append("<div class='card'>"+H(status)+"<strong>"+results.Values.Count(x=>(string)x["status"]==status)+"</strong></div>");b.Append("<div class='card'>Lỗi kỹ thuật<strong>"+TechnicalErrors+"</strong></div></div><div class='scroll'><table><thead><tr><th>Hồ sơ / chi nhánh</th><th>Tài khoản</th><th>Trạng thái cuối</th><th>Lý do từ chối / lỗi</th><th>Mã hệ thống</th></tr></thead><tbody>");
  foreach(var r in results.Values)b.Append("<tr><td>"+H(r["itemId"])+"<br>"+H(r["branch"])+"</td><td>"+H(r["account"])+"</td><td>"+H(r["status"])+((string)r["status"]=="Chờ duyệt"?"<br><small>Chưa hoàn tất sau vòng cuối</small>":"")+"</td><td>"+H(r["reason"])+"<br><span class='fail'>"+H(r["error"])+"</span></td><td><code>"+H(r["documentId"])+"</code></td></tr>");b.Append("</tbody></table></div><h2>Lịch sử từng hồ sơ</h2>");
  foreach(var r in results.Values){b.Append("<details><summary>"+H(r["itemId"])+" · "+H(r["status"])+"</summary><table><tr><th>Vòng</th><th>Trạng thái</th><th>Tài khoản</th><th>Lý do</th></tr>");foreach(Dictionary<string,object> h in (List<object>)r["history"])b.Append("<tr><td>"+H(h["round"])+"</td><td>"+H(h["status"])+"</td><td>"+H(h["account"])+"</td><td>"+H(h["reason"])+"</td></tr>");b.Append("</table></details>");}
  b.Append("<h2>Timeline thực thi</h2><p><a href='events.jsonl'>Event log</a> · <a href='results.json'>Kết quả JSON</a> · <a href='run.log'>Log dạng text</a></p>");foreach(var group in events.GroupBy(e=>(string)e["invocationId"])){b.Append("<details><summary>"+H(group.Key==""?"Điều phối native akaBot":group.First()["itemId"]+" / "+group.First()["scenarioId"]+" / vòng "+group.First()["round"])+"</summary><div class='scroll'><table><tr><th>Thời điểm UTC</th><th>Sự kiện</th><th>Bước / thử</th><th>Kết quả</th><th>Chi tiết</th></tr>");foreach(var e in group){string detail=H(e["detail"]);if((string)e["eventType"]=="ArtifactCreated")detail="<a href='"+H(e["detail"])+"'>"+H(e["detail"])+"</a>";b.Append("<tr><td><small>"+H(e["timestampUtc"])+"</small></td><td>"+H(e["eventType"])+"</td><td>"+H(e["stepId"])+" / "+H(e["attempt"])+"<br><small>"+H(e["sourceCell"])+"</small></td><td>"+H(e["status"])+"</td><td>"+detail+"</td></tr>");}b.Append("</table></div></details>");}b.Append("</main></html>");File.WriteAllText(Path.Combine(runDir,"report.html"),b.ToString(),new UTF8Encoding(false));
 }
}}
